# Generated by Django 5.2.4 on 2025-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
