# Generated by Django 5.2.4 on 2025-09-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0003_profile_coveragetype_profile_insurancecoverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('formType', models.CharField(choices=[('homepage', 'Homepage Form'), ('referral', 'Referral Friend Form'), ('appointment', 'Appointment Form')], db_index=True, help_text='Tipo de formulário submetido (igual aos tipos usados no site).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='company.company')),
                ('profile', models.ForeignKey(blank=True, help_text='Vincule esta submissão ao perfil do usuário, se aplicável.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='users.profile')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ('-created_at',),
            },
        ),
    ]
