# Generated by Django 5.2.4 on 2025-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formsubmission_formtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='formType',
            field=models.CharField(choices=[('homepage', 'Homepage Form'), ('referral', 'Referral Friend Form'), ('appointment', 'Appointment Form'), ('contact', 'Contact Form'), ('careers', 'Careers Form')], db_index=True, help_text='Tipo de formulário submetido (igual aos tipos usados no site).', max_length=20),
        ),
    ]
