# Generated by Django 5.2.4 on 2025-09-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formsubmission_formtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='phone',
        ),
    ]
