# Generated by Django 5.2.4 on 2025-09-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_formsubmission_email_and_more'),
        ('users', '0006_alter_profile_formtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='coverageType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='insuranceCoverage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='formType',
            field=models.CharField(choices=[('homepage', 'Homepage Form'), ('referral', 'Referral Friend Form'), ('appointment', 'Appointment Form'), ('contact', 'Contact Form'), ('careers', 'Careers Form')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='users.profile'),
        ),
    ]
