# Generated by Django 5.2.4 on 2025-09-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formsubmission_coveragetype_formsubmission_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='extra',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='householdIncome',
            field=models.CharField(blank=True, choices=[('0k-15k', '0k-15k'), ('15k-25k', '15k-25k'), ('30k-50k', '30k-50k'), ('50k-75k', '50k-75k'), ('75k-100k', '75k-100k')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='referrerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='referrerFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='zipCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='coverageType',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('family', 'Family')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='insuranceCoverage',
            field=models.CharField(blank=True, choices=[('Medicare', 'Medicare'), ('Dental', 'Dental'), ('Life', 'Life'), ('Health', 'Health'), ('Vision', 'Vision')], max_length=20, null=True),
        ),
    ]
