# Generated by Django 5.2.4 on 2025-09-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coverageType', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], max_length=20)),
                ('insuranceCoverage', models.CharField(choices=[('Medicare', 'Medicare'), ('Dental', 'Dental'), ('Life', 'Life'), ('Health', 'Health'), ('Vision', 'Vision')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
                'unique_together': {('company', 'name', 'coverageType', 'insuranceCoverage')},
            },
        ),
    ]
