# Generated by Django 4.2.19 on 2025-04-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("zipcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[("individual", "Individual"), ("family", "Family")],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("medicare", "Medicare"),
                            ("dental", "Dental"),
                            ("life", "Life"),
                            ("healthy", "Healthy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "income",
                    models.CharField(
                        choices=[
                            ("0k-15k", "0k-15k"),
                            ("15k-25k", "15k-25k"),
                            ("30k-50k", "30k-50k"),
                            ("50k-75k", "50k-75k"),
                            ("75k-100k", "75k-100k"),
                        ],
                        max_length=20,
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=255, null=True)),
                ("lastname", models.CharField(blank=True, max_length=255, null=True)),
                ("birth", models.DateField()),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Data",
                "verbose_name_plural": "Sheet Data",
            },
        ),
    ]
