# Generated by Django 4.2.19 on 2025-04-08 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sheetdata",
            old_name="zipcode",
            new_name="zipCode",
        ),
    ]
