# Generated by Django 4.2.19 on 2025-04-08 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0002_rename_zipcode_sheetdata_zipcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sheetdata",
            old_name="plan",
            new_name="coverageType",
        ),
    ]
