# Generated by Django 4.2.19 on 2025-04-08 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0003_rename_plan_sheetdata_coveragetype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sheetdata",
            old_name="income",
            new_name="householdIncome",
        ),
        migrations.RenameField(
            model_name="sheetdata",
            old_name="type",
            new_name="insuranceCoverage",
        ),
    ]
