# Generated by Django 4.2.19 on 2025-04-08 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0004_rename_income_sheetdata_householdincome_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sheetdata",
            old_name="birth",
            new_name="dob",
        ),
        migrations.RenameField(
            model_name="sheetdata",
            old_name="firstname",
            new_name="firstName",
        ),
        migrations.RenameField(
            model_name="sheetdata",
            old_name="lastname",
            new_name="lastName",
        ),
    ]
