# Generated by Django 4.2.19 on 2025-04-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0005_rename_birth_sheetdata_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheetdata",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
