# Generated by Django 4.2.19 on 2025-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0006_alter_sheetdata_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheetdata",
            name="insuranceCoverage",
            field=models.CharField(
                choices=[
                    ("Medicare", "Medicare"),
                    ("Dental", "Dental"),
                    ("Life", "Life"),
                    ("Healthy", "Healthy"),
                    ("Vision", "Vision"),
                ],
                max_length=20,
            ),
        ),
    ]
