# Generated by Django 4.2.19 on 2025-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheets", "0007_alter_sheetdata_insurancecoverage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sheetdata",
            name="spreadsheet_id",
        ),
        migrations.AlterField(
            model_name="sheetdata",
            name="insuranceCoverage",
            field=models.CharField(
                choices=[
                    ("Medicare", "Medicare"),
                    ("Dental", "Dental"),
                    ("Life", "Life"),
                    ("Health", "Health"),
                    ("Vision", "Vision"),
                ],
                max_length=20,
            ),
        ),
    ]
