# Generated by Django 5.2.4 on 2025-07-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('sheets', '0008_remove_sheetdata_spreadsheet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
