# Generated by Django 5.2.4 on 2025-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_alter_sheetdata_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetdata',
            name='formType',
            field=models.CharField(choices=[('homepage', 'Homepage Form'), ('referral', 'Referral Friend Form'), ('appointment', 'Appointment Form')], default='homepage', max_length=20),
        ),
    ]
