# Generated by Django 5.2.4 on 2025-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_sheetdata_formtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetdata',
            name='referrerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sheetdata',
            name='referrerFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
