# Generated by Django 5.2.4 on 2025-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverageType',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('family', 'Family')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insuranceCoverage',
            field=models.CharField(blank=True, choices=[('Medicare', 'Medicare'), ('Dental', 'Dental'), ('Life', 'Life'), ('Health', 'Health'), ('Vision', 'Vision')], max_length=20, null=True),
        ),
    ]
