# Generated by Django 5.2.4 on 2025-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_coveragetype_profile_insurancecoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='formType',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
