# Generated by Django 5.2.4 on 2025-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_formtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='formType',
            field=models.CharField(blank=True, choices=[('homepage', 'Homepage Form'), ('referral', 'Referral Friend Form'), ('appointment', 'Appointment Form')], max_length=20, null=True),
        ),
    ]
