# Generated by Django 5.2.4 on 2025-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_formtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='formType',
            field=models.CharField(blank=True, choices=[('homepage', 'Homepage Form'), ('referral', 'Referral Friend Form'), ('appointment', 'Appointment Form'), ('contact', 'Contact Form'), ('careers', 'Careers Form')], max_length=20, null=True),
        ),
    ]
